# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#from typing_extensions import IntVar
#from typing_extensions import IntVar

#from scipy.special._mptestutils import IntArg

import main
from main import *
from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 765)
        MainWindow.setStyleSheet("background-image: url(home.png);;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.all_page = QtWidgets.QStackedWidget(self.centralwidget)
        self.all_page.setObjectName("all_page")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background: transparent;\n"
"color : white;")
        self.home.setObjectName("home")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.home)
        self.horizontalLayout_28.setContentsMargins(10, 200, 1250, 200)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.widget = QtWidgets.QWidget(self.home)
        self.widget.setStyleSheet(" border-style: outset;\n"
" border-width: 3px;\n"
" border-radius: 50px;\n"
"border-color: #5682bf;")
        self.widget.setObjectName("widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_13.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("border:none;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_14.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.program_name_2 = QtWidgets.QPushButton(self.widget_2)
        self.program_name_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.program_name_2.setFont(font)
        self.program_name_2.setStyleSheet("background: transparent;\n"
"color : white;")
        self.program_name_2.setFlat(True)
        self.program_name_2.setObjectName("program_name_2")
        self.verticalLayout_14.addWidget(self.program_name_2)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_13.addWidget(self.line_6)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("border:none;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_15.setContentsMargins(10, 25, 10, 25)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.train_test_main_2 = QtWidgets.QPushButton(self.widget_3)

        def to_methodology_page(self):
                ui.all_page.setCurrentIndex(1)
        self.train_test_main_2.clicked.connect(to_methodology_page)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.train_test_main_2.setFont(font)
        self.train_test_main_2.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.train_test_main_2.setObjectName("train_test_main_2")
        self.verticalLayout_15.addWidget(self.train_test_main_2)
        self.predict_main_2 = QtWidgets.QPushButton(self.widget_3)
        def to_predict_page(self):
                ui.all_page.setCurrentIndex(2)
        self.predict_main_2.clicked.connect(to_predict_page)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.predict_main_2.setFont(font)
        self.predict_main_2.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.predict_main_2.setObjectName("predict_main_2")
        self.verticalLayout_15.addWidget(self.predict_main_2)
        self.exit_btn = QtWidgets.QPushButton(self.widget_3)
        self.exit_btn.clicked.connect(sys.exit)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_15.addWidget(self.exit_btn)
        self.verticalLayout_13.addWidget(self.widget_3)
        self.verticalLayout_13.setStretch(0, 3)
        self.verticalLayout_13.setStretch(2, 7)
        self.horizontalLayout_28.addWidget(self.widget)
        self.all_page.addWidget(self.home)
        self.train_test = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.train_test.setFont(font)
        self.train_test.setStyleSheet("background-image:url(:/img/back.png);\n"
"color:white;\n"
"color:white;\n"
" border-style: outset;\n"
" border-width: 3px;\n"
" border-radius: 50px;\n"
"border-color: #5682bf;\n"
"")
        self.train_test.setObjectName("train_test")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.train_test)
        self.gridLayout_2.setContentsMargins(75, 10, 75, 10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.box_container = QtWidgets.QWidget(self.train_test)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.box_container.setFont(font)
        self.box_container.setStyleSheet("border:none;\n"
"background: transparent;\n"
"")
        self.box_container.setObjectName("box_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.box_container)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.box_buton_train = QtWidgets.QWidget(self.box_container)
        self.box_buton_train.setObjectName("box_buton_train")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.box_buton_train)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.box_contain = QtWidgets.QWidget(self.box_buton_train)
        self.box_contain.setObjectName("box_contain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.box_contain)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        logistic_check_box = self.logistic_box = QtWidgets.QCheckBox(self.box_contain)
        self.logistic_box.setStyleSheet("")
        self.logistic_box.setObjectName("logistic_box")
        self.horizontalLayout.addWidget(self.logistic_box)
        svm_check_box = self.svm_box = QtWidgets.QCheckBox(self.box_contain)
        self.svm_box.setObjectName("svm_box")
        self.horizontalLayout.addWidget(self.svm_box)
        id3_check_box = self.id3_box = QtWidgets.QCheckBox(self.box_contain)
        self.id3_box.setObjectName("id3_box")
        self.horizontalLayout.addWidget(self.id3_box)
        naive_check_box = self.naive_box = QtWidgets.QCheckBox(self.box_contain)
        self.naive_box.setObjectName("naive_box")
        self.horizontalLayout.addWidget(self.naive_box)
        random_check_box = self.random_box = QtWidgets.QCheckBox(self.box_contain)
        self.random_box.setObjectName("random_box")
        self.horizontalLayout.addWidget(self.random_box)
        self.verticalLayout_3.addWidget(self.box_contain)
        self.btn_contain = QtWidgets.QWidget(self.box_buton_train)
        self.btn_contain.setObjectName("btn_contain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_contain)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.train_btn = QtWidgets.QPushButton(self.btn_contain)
        def algorithm_checked_train(self):
                if(logistic_check_box.isChecked()):
                        logistic_tr = logistic_train()
                        log_ac.setText(str(logistic_tr[0]))
                        log_pre.setText(str(logistic_tr[1]))
                        log_rec.setText(str(logistic_tr[2]))
                        log_f1.setText(str(logistic_tr[3]))
                else:
                        log_ac.setText("")
                        log_pre.setText("")
                        log_rec.setText("")
                        log_f1.setText("")
                if (svm_check_box.isChecked()):
                        svm_tr = svm_train()
                        sv_ac.setText(str(svm_tr[0]))
                        sv_pre.setText(str(svm_tr[1]))
                        sv_rec.setText(str(svm_tr[2]))
                        sv_f1.setText(str(svm_tr[3]))
                else:
                        sv_ac.setText("")
                        sv_pre.setText("")
                        sv_rec.setText("")
                        sv_f1.setText("")
                if (id3_check_box.isChecked()):
                        id3_tr = Decision_train()
                        id_acu.setText(str(id3_tr[0]))
                        id_pre.setText(str(id3_tr[1]))
                        id_rec.setText(str(id3_tr[2]))
                        id_f1.setText(str(id3_tr[3]))
                else:
                        id_acu.setText("")
                        id_pre.setText("")
                        id_rec.setText("")
                        id_f1.setText("")
                if (naive_check_box.isChecked()):
                        naive_tr = Naive_train()
                        nai_acu.setText(str(naive_tr[0]))
                        nai_pre.setText(str(naive_tr[1]))
                        nai_rec.setText(str(naive_tr[2]))
                        nai_f1.setText(str(naive_tr[3]))
                else:
                        nai_acu.setText("")
                        nai_pre.setText("")
                        nai_rec.setText("")
                        nai_f1.setText("")
                if (random_check_box.isChecked()):
                        random_tr = Random_Train()
                        ran_acu.setText(str(random_tr[0]))
                        ran_pre.setText(str(random_tr[1]))
                        ran_rec.setText(str(random_tr[2]))
                        ran_f1.setText(str(random_tr[3]))
                else:
                        ran_acu.setText("")
                        ran_pre.setText("")
                        ran_rec.setText("")
                        ran_f1.setText("")
        self.train_btn.clicked.connect(algorithm_checked_train)
        self.train_btn.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.train_btn.setFont(font)
        self.train_btn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.train_btn.setObjectName("train_btn")
        self.horizontalLayout_2.addWidget(self.train_btn)
        self.test_btn = QtWidgets.QPushButton(self.btn_contain)
        self.test_btn.setMaximumSize(QtCore.QSize(500, 16777215))
        def algorithm_checked_test(self):
                if(logistic_check_box.isChecked()):
                        logistic_ts = logistic_test()
                        log_acu_2.setText(str(logistic_ts[0]))
                        log_pre_2.setText(str(logistic_ts[1]))
                        log_rec_2.setText(str(logistic_ts[2]))
                        log_f1_2.setText(str(logistic_ts[3]))
                else:
                        log_acu_2.setText("")
                        log_pre_2.setText("")
                        log_rec_2.setText("")
                        log_f1_2.setText("")
                if (svm_check_box.isChecked()):
                        svm_ts = svm_test()
                        svm_acu_2.setText(str(svm_ts[0]))
                        svm_pre_2.setText(str(svm_ts[1]))
                        svm_rec_2.setText(str(svm_ts[2]))
                        svm_f1_2.setText(str(svm_ts[3]))
                else:
                        svm_acu_2.setText("")
                        svm_pre_2.setText("")
                        svm_rec_2.setText("")
                        svm_f1_2.setText("")
                if (id3_check_box.isChecked()):
                        id3_ts = Decision_test()
                        id_acu_2.setText(str(id3_ts[0]))
                        id_pre_2.setText(str(id3_ts[1]))
                        id_rec_2.setText(str(id3_ts[2]))
                        id_f1_2.setText(str(id3_ts[3]))
                else:
                        id_acu_2.setText("")
                        id_pre_2.setText("")
                        id_rec_2.setText("")
                        id_f1_2.setText("")
                if (naive_check_box.isChecked()):
                        naive_ts = Naive_test()
                        nai_acu_2.setText(str(naive_ts[0]))
                        nai_pre_2.setText(str(naive_ts[1]))
                        nai_rec_2.setText(str(naive_ts[2]))
                        nai_f1_2.setText(str(naive_ts[3]))
                else:
                        nai_acu_2.setText("")
                        nai_pre_2.setText("")
                        nai_rec_2.setText("")
                        nai_f1_2.setText("")
                if (random_check_box.isChecked()):
                        random_ts = Random_Test()
                        ran_acu_2.setText(str(random_ts[0]))
                        ran_pre_2.setText(str(random_ts[1]))
                        ran_rec_2.setText(str(random_ts[2]))
                        ran_f1_2.setText(str(random_ts[3]))
                else:
                        ran_acu_2.setText("")
                        ran_pre_2.setText("")
                        ran_rec_2.setText("")
                        ran_f1_2.setText("")

        self.test_btn.clicked.connect(algorithm_checked_test)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.test_btn.setFont(font)
        self.test_btn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.test_btn.setObjectName("test_btn")
        self.horizontalLayout_2.addWidget(self.test_btn)
        self.back_btn = QtWidgets.QPushButton(self.btn_contain)

        self.back_btn.setMaximumSize(QtCore.QSize(500, 16777215))
        def to_home_page(self):
                ui.all_page.setCurrentIndex(0)
        self.back_btn.clicked.connect(to_home_page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_2.addWidget(self.back_btn)
        self.verticalLayout_3.addWidget(self.btn_contain)
        self.verticalLayout_2.addWidget(self.box_buton_train)
        self.line_5 = QtWidgets.QFrame(self.box_container)
        self.line_5.setStyleSheet("background: white;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.label_container = QtWidgets.QWidget(self.box_container)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_container.setFont(font)
        self.label_container.setStyleSheet("font-size: 15px")
        self.label_container.setObjectName("label_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.label_container)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logistic_train_test = QtWidgets.QWidget(self.label_container)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.logistic_train_test.setFont(font)
        self.logistic_train_test.setObjectName("logistic_train_test")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.logistic_train_test)
        self.verticalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logistic_row_1 = QtWidgets.QWidget(self.logistic_train_test)
        self.logistic_row_1.setObjectName("logistic_row_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logistic_row_1)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_1 = QtWidgets.QLabel(self.logistic_row_1)
        self.lb_1.setObjectName("lb_1")
        self.horizontalLayout_3.addWidget(self.lb_1)
        self.lb_2 = QtWidgets.QLabel(self.logistic_row_1)
        self.lb_2.setObjectName("lb_2")
        self.horizontalLayout_3.addWidget(self.lb_2)
        self.lb_3 = QtWidgets.QLabel(self.logistic_row_1)
        self.lb_3.setObjectName("lb_3")
        self.horizontalLayout_3.addWidget(self.lb_3)
        self.lb_4 = QtWidgets.QLabel(self.logistic_row_1)
        self.lb_4.setObjectName("lb_4")
        self.horizontalLayout_3.addWidget(self.lb_4)
        self.lb_5 = QtWidgets.QLabel(self.logistic_row_1)
        self.lb_5.setObjectName("lb_5")
        self.horizontalLayout_3.addWidget(self.lb_5)
        self.verticalLayout_5.addWidget(self.logistic_row_1)
        self.logistic_row_2 = QtWidgets.QWidget(self.logistic_train_test)
        self.logistic_row_2.setObjectName("logistic_row_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.logistic_row_2)
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_6 = QtWidgets.QLabel(self.logistic_row_2)
        self.lb_6.setObjectName("lb_6")
        self.horizontalLayout_4.addWidget(self.lb_6)
        log_ac = self.lb_7 = QtWidgets.QLabel(self.logistic_row_2)
        self.lb_7.setText("")
        self.lb_7.setObjectName("lb_7")
        self.horizontalLayout_4.addWidget(self.lb_7)
        log_pre = self.lb_9 = QtWidgets.QLabel(self.logistic_row_2)
        self.lb_9.setText("")
        self.lb_9.setObjectName("lb_9")
        self.horizontalLayout_4.addWidget(self.lb_9)
        log_rec = self.lb_8 = QtWidgets.QLabel(self.logistic_row_2)
        self.lb_8.setText("")
        self.lb_8.setObjectName("lb_8")
        self.horizontalLayout_4.addWidget(self.lb_8)
        log_f1 = self.lb_10 = QtWidgets.QLabel(self.logistic_row_2)
        self.lb_10.setText("")
        self.lb_10.setObjectName("lb_10")
        self.horizontalLayout_4.addWidget(self.lb_10)
        self.verticalLayout_5.addWidget(self.logistic_row_2)
        self.logistic_row_3 = QtWidgets.QWidget(self.logistic_train_test)
        self.logistic_row_3.setObjectName("logistic_row_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.logistic_row_3)
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_11 = QtWidgets.QLabel(self.logistic_row_3)
        self.lb_11.setObjectName("lb_11")
        self.horizontalLayout_5.addWidget(self.lb_11)
        log_acu_2 = self.lb_12 = QtWidgets.QLabel(self.logistic_row_3)
        self.lb_12.setText("")
        self.lb_12.setObjectName("lb_12")
        self.horizontalLayout_5.addWidget(self.lb_12)
        log_pre_2 = self.lb_14 = QtWidgets.QLabel(self.logistic_row_3)
        self.lb_14.setText("")
        self.lb_14.setObjectName("lb_14")
        self.horizontalLayout_5.addWidget(self.lb_14)
        log_rec_2 = self.lb_13 = QtWidgets.QLabel(self.logistic_row_3)
        self.lb_13.setText("")
        self.lb_13.setObjectName("lb_13")
        self.horizontalLayout_5.addWidget(self.lb_13)
        log_f1_2 = self.lb_15 = QtWidgets.QLabel(self.logistic_row_3)
        self.lb_15.setText("")
        self.lb_15.setObjectName("lb_15")
        self.horizontalLayout_5.addWidget(self.lb_15)
        self.verticalLayout_5.addWidget(self.logistic_row_3)
        self.verticalLayout_4.addWidget(self.logistic_train_test)
        self.line = QtWidgets.QFrame(self.label_container)
        self.line.setStyleSheet("background: white;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.svm_train_test = QtWidgets.QWidget(self.label_container)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.svm_train_test.setFont(font)
        self.svm_train_test.setObjectName("svm_train_test")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.svm_train_test)
        self.verticalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.svm_row_1 = QtWidgets.QWidget(self.svm_train_test)
        self.svm_row_1.setObjectName("svm_row_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.svm_row_1)
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_16 = QtWidgets.QLabel(self.svm_row_1)
        self.lb_16.setObjectName("lb_16")
        self.horizontalLayout_6.addWidget(self.lb_16)
        self.lb_17 = QtWidgets.QLabel(self.svm_row_1)
        self.lb_17.setObjectName("lb_17")
        self.horizontalLayout_6.addWidget(self.lb_17)
        self.lb_19 = QtWidgets.QLabel(self.svm_row_1)
        self.lb_19.setObjectName("lb_19")
        self.horizontalLayout_6.addWidget(self.lb_19)
        self.lb_18 = QtWidgets.QLabel(self.svm_row_1)
        self.lb_18.setObjectName("lb_18")
        self.horizontalLayout_6.addWidget(self.lb_18)
        self.lb_20 = QtWidgets.QLabel(self.svm_row_1)
        self.lb_20.setObjectName("lb_20")
        self.horizontalLayout_6.addWidget(self.lb_20)
        self.verticalLayout_6.addWidget(self.svm_row_1)
        self.svm_raw_2 = QtWidgets.QWidget(self.svm_train_test)
        self.svm_raw_2.setObjectName("svm_raw_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.svm_raw_2)
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_24 = QtWidgets.QLabel(self.svm_raw_2)
        self.lb_24.setObjectName("lb_24")
        self.horizontalLayout_7.addWidget(self.lb_24)
        sv_ac = self.lb_23 = QtWidgets.QLabel(self.svm_raw_2)
        self.lb_23.setText("")
        self.lb_23.setObjectName("lb_23")
        self.horizontalLayout_7.addWidget(self.lb_23)
        sv_pre = self.lb_25 = QtWidgets.QLabel(self.svm_raw_2)
        self.lb_25.setText("")
        self.lb_25.setObjectName("lb_25")
        self.horizontalLayout_7.addWidget(self.lb_25)
        sv_rec = self.lb_21 = QtWidgets.QLabel(self.svm_raw_2)
        self.lb_21.setText("")
        self.lb_21.setObjectName("lb_21")
        self.horizontalLayout_7.addWidget(self.lb_21)
        sv_f1 = self.lb_22 = QtWidgets.QLabel(self.svm_raw_2)
        self.lb_22.setText("")
        self.lb_22.setObjectName("lb_22")
        self.horizontalLayout_7.addWidget(self.lb_22)
        self.verticalLayout_6.addWidget(self.svm_raw_2)
        self.svm_raw_3 = QtWidgets.QWidget(self.svm_train_test)
        self.svm_raw_3.setObjectName("svm_raw_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.svm_raw_3)
        self.horizontalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_26 = QtWidgets.QLabel(self.svm_raw_3)
        self.lb_26.setObjectName("lb_26")
        self.horizontalLayout_8.addWidget(self.lb_26)
        svm_acu_2 = self.lb_29 = QtWidgets.QLabel(self.svm_raw_3)
        self.lb_29.setText("")
        self.lb_29.setObjectName("lb_29")
        self.horizontalLayout_8.addWidget(self.lb_29)
        svm_pre_2 = self.lb_27 = QtWidgets.QLabel(self.svm_raw_3)
        self.lb_27.setText("")
        self.lb_27.setObjectName("lb_27")
        self.horizontalLayout_8.addWidget(self.lb_27)
        svm_rec_2 = self.lb_28 = QtWidgets.QLabel(self.svm_raw_3)
        self.lb_28.setText("")
        self.lb_28.setObjectName("lb_28")
        self.horizontalLayout_8.addWidget(self.lb_28)
        svm_f1_2 = self.lb_30 = QtWidgets.QLabel(self.svm_raw_3)
        self.lb_30.setText("")
        self.lb_30.setObjectName("lb_30")
        self.horizontalLayout_8.addWidget(self.lb_30)
        self.verticalLayout_6.addWidget(self.svm_raw_3)
        self.verticalLayout_4.addWidget(self.svm_train_test)
        self.line_2 = QtWidgets.QFrame(self.label_container)
        self.line_2.setStyleSheet("background: white;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.id3_train_test = QtWidgets.QWidget(self.label_container)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.id3_train_test.setFont(font)
        self.id3_train_test.setObjectName("id3_train_test")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.id3_train_test)
        self.verticalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.id3_raw_1 = QtWidgets.QWidget(self.id3_train_test)
        self.id3_raw_1.setObjectName("id3_raw_1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.id3_raw_1)
        self.horizontalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lb_31 = QtWidgets.QLabel(self.id3_raw_1)
        self.lb_31.setObjectName("lb_31")
        self.horizontalLayout_9.addWidget(self.lb_31)
        self.lb_32 = QtWidgets.QLabel(self.id3_raw_1)
        self.lb_32.setObjectName("lb_32")
        self.horizontalLayout_9.addWidget(self.lb_32)
        self.lb_34 = QtWidgets.QLabel(self.id3_raw_1)
        self.lb_34.setObjectName("lb_34")
        self.horizontalLayout_9.addWidget(self.lb_34)
        self.lb_33 = QtWidgets.QLabel(self.id3_raw_1)
        self.lb_33.setObjectName("lb_33")
        self.horizontalLayout_9.addWidget(self.lb_33)
        self.lb_35 = QtWidgets.QLabel(self.id3_raw_1)
        self.lb_35.setObjectName("lb_35")
        self.horizontalLayout_9.addWidget(self.lb_35)
        self.verticalLayout_7.addWidget(self.id3_raw_1)
        self.id3__raw_2 = QtWidgets.QWidget(self.id3_train_test)
        self.id3__raw_2.setObjectName("id3__raw_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.id3__raw_2)
        self.horizontalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lb_39 = QtWidgets.QLabel(self.id3__raw_2)
        self.lb_39.setObjectName("lb_39")
        self.horizontalLayout_10.addWidget(self.lb_39)
        id_acu = self.lb_38 = QtWidgets.QLabel(self.id3__raw_2)
        self.lb_38.setText("")
        self.lb_38.setObjectName("lb_38")
        self.horizontalLayout_10.addWidget(self.lb_38)
        id_pre = self.lb_40 = QtWidgets.QLabel(self.id3__raw_2)
        self.lb_40.setText("")
        self.lb_40.setObjectName("lb_40")
        self.horizontalLayout_10.addWidget(self.lb_40)
        id_rec = self.lb_36 = QtWidgets.QLabel(self.id3__raw_2)
        self.lb_36.setText("")
        self.lb_36.setObjectName("lb_36")
        self.horizontalLayout_10.addWidget(self.lb_36)
        id_f1 = self.lb_37 = QtWidgets.QLabel(self.id3__raw_2)
        self.lb_37.setText("")
        self.lb_37.setObjectName("lb_37")
        self.horizontalLayout_10.addWidget(self.lb_37)
        self.verticalLayout_7.addWidget(self.id3__raw_2)
        self.id3_raw_3 = QtWidgets.QWidget(self.id3_train_test)
        self.id3_raw_3.setObjectName("id3_raw_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.id3_raw_3)
        self.horizontalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lb_41 = QtWidgets.QLabel(self.id3_raw_3)
        self.lb_41.setObjectName("lb_41")
        self.horizontalLayout_11.addWidget(self.lb_41)
        id_acu_2 = self.lb_44 = QtWidgets.QLabel(self.id3_raw_3)
        self.lb_44.setText("")
        self.lb_44.setObjectName("lb_44")
        self.horizontalLayout_11.addWidget(self.lb_44)
        id_pre_2 = self.lb_42 = QtWidgets.QLabel(self.id3_raw_3)
        self.lb_42.setText("")
        self.lb_42.setObjectName("lb_42")
        self.horizontalLayout_11.addWidget(self.lb_42)
        id_rec_2 = self.lb_43 = QtWidgets.QLabel(self.id3_raw_3)
        self.lb_43.setText("")
        self.lb_43.setObjectName("lb_43")
        self.horizontalLayout_11.addWidget(self.lb_43)
        id_f1_2 = self.lb_45 = QtWidgets.QLabel(self.id3_raw_3)
        self.lb_45.setText("")
        self.lb_45.setObjectName("lb_45")
        self.horizontalLayout_11.addWidget(self.lb_45)
        self.verticalLayout_7.addWidget(self.id3_raw_3)
        self.verticalLayout_4.addWidget(self.id3_train_test)
        self.line_3 = QtWidgets.QFrame(self.label_container)
        self.line_3.setStyleSheet("background: white;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.naive_train_test = QtWidgets.QWidget(self.label_container)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.naive_train_test.setFont(font)
        self.naive_train_test.setObjectName("naive_train_test")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.naive_train_test)
        self.verticalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.naive_row_1 = QtWidgets.QWidget(self.naive_train_test)
        self.naive_row_1.setObjectName("naive_row_1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.naive_row_1)
        self.horizontalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lb_48 = QtWidgets.QLabel(self.naive_row_1)
        self.lb_48.setObjectName("lb_48")
        self.horizontalLayout_12.addWidget(self.lb_48)
        self.lb_46 = QtWidgets.QLabel(self.naive_row_1)
        self.lb_46.setObjectName("lb_46")
        self.horizontalLayout_12.addWidget(self.lb_46)
        self.lb_49 = QtWidgets.QLabel(self.naive_row_1)
        self.lb_49.setObjectName("lb_49")
        self.horizontalLayout_12.addWidget(self.lb_49)
        self.lb_47 = QtWidgets.QLabel(self.naive_row_1)
        self.lb_47.setObjectName("lb_47")
        self.horizontalLayout_12.addWidget(self.lb_47)
        self.lb_50 = QtWidgets.QLabel(self.naive_row_1)
        self.lb_50.setObjectName("lb_50")
        self.horizontalLayout_12.addWidget(self.lb_50)
        self.verticalLayout_8.addWidget(self.naive_row_1)
        self.naive_raw_2 = QtWidgets.QWidget(self.naive_train_test)
        self.naive_raw_2.setObjectName("naive_raw_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.naive_raw_2)
        self.horizontalLayout_13.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lb_51 = QtWidgets.QLabel(self.naive_raw_2)
        self.lb_51.setObjectName("lb_51")
        self.horizontalLayout_13.addWidget(self.lb_51)
        nai_acu = self.lb_53 = QtWidgets.QLabel(self.naive_raw_2)
        self.lb_53.setText("")
        self.lb_53.setObjectName("lb_53")
        self.horizontalLayout_13.addWidget(self.lb_53)
        nai_pre = self.lb_54 = QtWidgets.QLabel(self.naive_raw_2)
        self.lb_54.setText("")
        self.lb_54.setObjectName("lb_54")
        self.horizontalLayout_13.addWidget(self.lb_54)
        nai_rec = self.lb_55 = QtWidgets.QLabel(self.naive_raw_2)
        self.lb_55.setText("")
        self.lb_55.setObjectName("lb_55")
        self.horizontalLayout_13.addWidget(self.lb_55)
        nai_f1 = self.lb_52 = QtWidgets.QLabel(self.naive_raw_2)
        self.lb_52.setText("")
        self.lb_52.setObjectName("lb_52")
        self.horizontalLayout_13.addWidget(self.lb_52)
        self.verticalLayout_8.addWidget(self.naive_raw_2)
        self.naive_raw_3 = QtWidgets.QWidget(self.naive_train_test)
        self.naive_raw_3.setObjectName("naive_raw_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.naive_raw_3)
        self.horizontalLayout_14.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lb_59 = QtWidgets.QLabel(self.naive_raw_3)
        self.lb_59.setObjectName("lb_59")
        self.horizontalLayout_14.addWidget(self.lb_59)
        nai_acu_2 = self.lb_60 = QtWidgets.QLabel(self.naive_raw_3)
        self.lb_60.setText("")
        self.lb_60.setObjectName("lb_60")
        self.horizontalLayout_14.addWidget(self.lb_60)
        nai_pre_2 = self.lb_57 = QtWidgets.QLabel(self.naive_raw_3)
        self.lb_57.setText("")
        self.lb_57.setObjectName("lb_57")
        self.horizontalLayout_14.addWidget(self.lb_57)
        nai_rec_2 = self.lb_56 = QtWidgets.QLabel(self.naive_raw_3)
        self.lb_56.setText("")
        self.lb_56.setObjectName("lb_56")
        self.horizontalLayout_14.addWidget(self.lb_56)
        nai_f1_2 = self.lb_58 = QtWidgets.QLabel(self.naive_raw_3)
        self.lb_58.setText("")
        self.lb_58.setObjectName("lb_58")
        self.horizontalLayout_14.addWidget(self.lb_58)
        self.verticalLayout_8.addWidget(self.naive_raw_3)
        self.verticalLayout_4.addWidget(self.naive_train_test)
        self.line_4 = QtWidgets.QFrame(self.label_container)
        self.line_4.setStyleSheet("background: white;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.random_train_test = QtWidgets.QWidget(self.label_container)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.random_train_test.setFont(font)
        self.random_train_test.setObjectName("random_train_test")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.random_train_test)
        self.verticalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.random_raw_1 = QtWidgets.QWidget(self.random_train_test)
        self.random_raw_1.setObjectName("random_raw_1")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.random_raw_1)
        self.horizontalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lb_63 = QtWidgets.QLabel(self.random_raw_1)
        self.lb_63.setObjectName("lb_63")
        self.horizontalLayout_15.addWidget(self.lb_63)
        self.lb_61 = QtWidgets.QLabel(self.random_raw_1)
        self.lb_61.setObjectName("lb_61")
        self.horizontalLayout_15.addWidget(self.lb_61)
        self.lb_64 = QtWidgets.QLabel(self.random_raw_1)
        self.lb_64.setObjectName("lb_64")
        self.horizontalLayout_15.addWidget(self.lb_64)
        self.lb_62 = QtWidgets.QLabel(self.random_raw_1)
        self.lb_62.setObjectName("lb_62")
        self.horizontalLayout_15.addWidget(self.lb_62)
        self.lb_65 = QtWidgets.QLabel(self.random_raw_1)
        self.lb_65.setObjectName("lb_65")
        self.horizontalLayout_15.addWidget(self.lb_65)
        self.verticalLayout_9.addWidget(self.random_raw_1)
        self.random_raw_2 = QtWidgets.QWidget(self.random_train_test)
        self.random_raw_2.setObjectName("random_raw_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.random_raw_2)
        self.horizontalLayout_16.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lb_66 = QtWidgets.QLabel(self.random_raw_2)
        self.lb_66.setObjectName("lb_66")
        self.horizontalLayout_16.addWidget(self.lb_66)
        ran_acu = self.lb_68 = QtWidgets.QLabel(self.random_raw_2)
        self.lb_68.setText("")
        self.lb_68.setObjectName("lb_68")
        self.horizontalLayout_16.addWidget(self.lb_68)
        ran_pre = self.lb_69 = QtWidgets.QLabel(self.random_raw_2)
        self.lb_69.setText("")
        self.lb_69.setObjectName("lb_69")
        self.horizontalLayout_16.addWidget(self.lb_69)
        ran_rec = self.lb_70 = QtWidgets.QLabel(self.random_raw_2)
        self.lb_70.setText("")
        self.lb_70.setObjectName("lb_70")
        self.horizontalLayout_16.addWidget(self.lb_70)
        ran_f1 = self.lb_67 = QtWidgets.QLabel(self.random_raw_2)
        self.lb_67.setText("")
        self.lb_67.setObjectName("lb_67")
        self.horizontalLayout_16.addWidget(self.lb_67)
        self.verticalLayout_9.addWidget(self.random_raw_2)
        self.random_raw_3 = QtWidgets.QWidget(self.random_train_test)
        self.random_raw_3.setObjectName("random_raw_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.random_raw_3)
        self.horizontalLayout_17.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lb_74 = QtWidgets.QLabel(self.random_raw_3)
        self.lb_74.setObjectName("lb_74")
        self.horizontalLayout_17.addWidget(self.lb_74)
        ran_acu_2 = self.lb_75 = QtWidgets.QLabel(self.random_raw_3)
        self.lb_75.setText("")
        self.lb_75.setObjectName("lb_75")
        self.horizontalLayout_17.addWidget(self.lb_75)
        ran_pre_2 = self.lb_72 = QtWidgets.QLabel(self.random_raw_3)
        self.lb_72.setText("")
        self.lb_72.setObjectName("lb_72")
        self.horizontalLayout_17.addWidget(self.lb_72)
        ran_rec_2 = self.lb_71 = QtWidgets.QLabel(self.random_raw_3)
        self.lb_71.setText("")
        self.lb_71.setObjectName("lb_71")
        self.horizontalLayout_17.addWidget(self.lb_71)
        ran_f1_2 = self.lb_73 = QtWidgets.QLabel(self.random_raw_3)
        self.lb_73.setText("")
        self.lb_73.setObjectName("lb_73")
        self.horizontalLayout_17.addWidget(self.lb_73)
        self.verticalLayout_9.addWidget(self.random_raw_3)
        self.verticalLayout_4.addWidget(self.random_train_test)
        self.verticalLayout_2.addWidget(self.label_container)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(2, 8)
        self.gridLayout_2.addWidget(self.box_container, 0, 0, 1, 1)
        self.all_page.addWidget(self.train_test)
        self.customer = QtWidgets.QWidget()
        self.customer.setStyleSheet("background-image:url(:/img/back.png);\n"
"color:white;\n"
" border-style: outset;\n"
" border-width: 3px;\n"
" border-radius: 50px;\n"
"border-color: #5682bf;\n"
"")
        self.customer.setObjectName("customer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.customer)
        self.gridLayout_3.setContentsMargins(75, 50, 75, 50)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.customer_container = QtWidgets.QWidget(self.customer)
        self.customer_container.setStyleSheet("background: transparent;\n"
"border:none;\n"
"\n"
"")
        self.customer_container.setObjectName("customer_container")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.customer_container)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.customer_data_box = QtWidgets.QWidget(self.customer_container)
        self.customer_data_box.setStyleSheet("QLineEdit { border : 0px;\n"
"border-bottom : 2px solid #95b7e5;\n"
"padding-bottom:10px; }")

        self.customer_data_box.setObjectName("customer_data_box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.customer_data_box)
        self.verticalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.raw_1 = QtWidgets.QWidget(self.customer_data_box)
        self.raw_1.setObjectName("raw_1")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.raw_1)
        self.horizontalLayout_18.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_18.setSpacing(100)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        cust_id = self.customer_id = QtWidgets.QLineEdit(self.raw_1)

        font = QtGui.QFont()
        font.setPointSize(15)
        self.customer_id.setFont(font)
        self.customer_id.setStyleSheet("")
        self.customer_id.setAlignment(QtCore.Qt.AlignCenter)
        self.customer_id.setObjectName("customer_id")
        self.horizontalLayout_18.addWidget(self.customer_id)
        self.gender = QtWidgets.QLineEdit(self.raw_1)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.gender.setFont(font)
        self.gender.setAlignment(QtCore.Qt.AlignCenter)
        self.gender.setObjectName("gender")
        self.horizontalLayout_18.addWidget(self.gender)
        self.senior_sitizen = QtWidgets.QLineEdit(self.raw_1)

        font = QtGui.QFont()
        font.setPointSize(15)
        self.senior_sitizen.setFont(font)
        self.senior_sitizen.setAlignment(QtCore.Qt.AlignCenter)
        self.senior_sitizen.setObjectName("senior_sitizen")
        self.horizontalLayout_18.addWidget(self.senior_sitizen)
        self.verticalLayout_11.addWidget(self.raw_1)
        self.raw_2 = QtWidgets.QWidget(self.customer_data_box)
        self.raw_2.setObjectName("raw_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.raw_2)
        self.horizontalLayout_19.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_19.setSpacing(100)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.partner = QtWidgets.QLineEdit(self.raw_2)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.partner.setFont(font)
        self.partner.setStyleSheet("")
        self.partner.setAlignment(QtCore.Qt.AlignCenter)
        self.partner.setObjectName("partner")
        self.horizontalLayout_19.addWidget(self.partner)
        self.dependent = QtWidgets.QLineEdit(self.raw_2)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.dependent.setFont(font)
        self.dependent.setAlignment(QtCore.Qt.AlignCenter)
        self.dependent.setObjectName("dependent")
        self.horizontalLayout_19.addWidget(self.dependent)




        self.tenure = QtWidgets.QLineEdit(self.raw_2)

        # , , , ,
        # , , , ,
        # , , , ,
        # , , , ,
        # , , ):
        # def check_types():
        #         data = [19]
        #         self.data[0] = str(self.gender.text())
        #         self.data[1] = str(self.senior_sitizen.text())
        #         self.data[2] = str(self.partner.text())
        #         self.data[3] = str(self.dependent.text())
        #         self.data[4] = str(self.tenure.text())
        #         self.data[5] = str(self.phone_service.text())
        #         self.data[6] = str(self.multiple_lines.text())
        #         self.data[7] = str(self.internet_service.text())
        #         self.data[8] = str(self.online_security.text())
        #         self.data[9] = str(self.onlin_backup.text())
        #         self.data[10] = str(self.device_protection.text())
        #         self.data[11] = str(self.tech_support.text())
        #         self.data[12] = str(self.streaming_tv.text())
        #         self.data[13] = str(self.streaming_movies.text())
        #         self.data[14] = str(self.contract.text())
        #         self.data[15] = str(self.paperless_billing.text())
        #         self.data[16] = str(self.payment_method.text())
        #         self.data[17] = str(self.monthly_charges.text())
        #         self.data[18] = str(self.total_charges.text())
        #         return data
        #
        #
        # def algo_predict(self):
        #         #cust_id_val = cust_id.text()
        #
        #         #gender_val = gender.text()
        #         #tenure_val = tenure.text()
        #         #partner_val = partner.text()
        #         #internet_service_val = internet_service.text()
        #         #senior_val = senior.text()
        #         #dependent_val = dependent.text()
        #         #onlin_backup_val = onlin_backup.text()
        #         #streaming_movies_val = streaming_movies.text()
        #         #device_protection_val = device_protection.text()
        #         #multiple_lines_val = multiple_lines.text()
        #         #phone_service_val = phone_service.text()
        #         #tech_support_val = tech_support.text()
        #         #streaming_tv_val = streaming_tv.text()
        #         #total_charges_val = total_charges.text()
        #         #monthly_charges_val = monthly_charges.text()
        #         #payment_method_val = payment_method.text()
        #         #paperless_billing_val = paperless_billing.text()
        #         #contract_val = contract.text()
        #         #online_security_val = online_security.text()
        #         data = check_types
        #         log = logistic_pridect(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18])
        #         if(log[0] == 1):
        #                 algo_1_answer_txt.setText("Yes")
        #         else:
        #                 algo_1_answer_txt.setText("No")
        #         svm_predict = svm_pridect(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18])
        #         if (svm_predict[0] == 1):
        #                 algo_2_answer_txt.setText("Yes")
        #         else:
        #                 algo_2_answer_txt.setText("No")
        #         id3_predict = DecicionTree_pridect(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18])
        #         if (id3_predict[0] == 1):
        #                 algo_3_answer_txt.setText("Yes")
        #         else:
        #                 algo_3_answer_txt.setText("No")
        #         naive_predict = Naive_pridect(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18])
        #         if (naive_predict[0] == 1):
        #                 algo_4_answer_txt.setText("Yes")
        #         else:
        #                 algo_4_answer_txt.setText("No")
        #         random_predict = Random_pridect(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18])
        #         if (random_predict[0] == 1):
        #                 algo_5_answer_txt.setText("Yes")
        #         else:
        #                 algo_5_answer_txt.setText("No")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tenure.setFont(font)
        self.tenure.setAlignment(QtCore.Qt.AlignCenter)
        self.tenure.setObjectName("tenure")
        self.horizontalLayout_19.addWidget(self.tenure)
        self.verticalLayout_11.addWidget(self.raw_2)
        self.raw_3 = QtWidgets.QWidget(self.customer_data_box)
        self.raw_3.setObjectName("raw_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.raw_3)
        self.horizontalLayout_20.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_20.setSpacing(100)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.phone_service = QtWidgets.QLineEdit(self.raw_3)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.phone_service.setFont(font)
        self.phone_service.setAlignment(QtCore.Qt.AlignCenter)
        self.phone_service.setObjectName("phone_service")
        self.horizontalLayout_20.addWidget(self.phone_service)
        self.multiple_lines = QtWidgets.QLineEdit(self.raw_3)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.multiple_lines.setFont(font)
        self.multiple_lines.setAlignment(QtCore.Qt.AlignCenter)
        self.multiple_lines.setObjectName("multiple_lines")
        self.horizontalLayout_20.addWidget(self.multiple_lines)
        self.internet_service = QtWidgets.QLineEdit(self.raw_3)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.internet_service.setFont(font)
        self.internet_service.setAlignment(QtCore.Qt.AlignCenter)
        self.internet_service.setObjectName("internet_service")
        self.horizontalLayout_20.addWidget(self.internet_service)
        self.verticalLayout_11.addWidget(self.raw_3)
        self.raw_4 = QtWidgets.QWidget(self.customer_data_box)
        self.raw_4.setObjectName("raw_4")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.raw_4)
        self.horizontalLayout_22.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_22.setSpacing(100)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.online_security = QtWidgets.QLineEdit(self.raw_4)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.online_security.setFont(font)
        self.online_security.setAlignment(QtCore.Qt.AlignCenter)
        self.online_security.setObjectName("online_security")
        self.horizontalLayout_22.addWidget(self.online_security)
        self.onlin_backup = QtWidgets.QLineEdit(self.raw_4)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.onlin_backup.setFont(font)
        self.onlin_backup.setAlignment(QtCore.Qt.AlignCenter)
        self.onlin_backup.setObjectName("onlin_backup")
        self.horizontalLayout_22.addWidget(self.onlin_backup)
        self.device_protection = QtWidgets.QLineEdit(self.raw_4)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.device_protection.setFont(font)
        self.device_protection.setAlignment(QtCore.Qt.AlignCenter)
        self.device_protection.setObjectName("device_protection")
        self.horizontalLayout_22.addWidget(self.device_protection)
        self.verticalLayout_11.addWidget(self.raw_4)
        self.raw_5 = QtWidgets.QWidget(self.customer_data_box)
        self.raw_5.setObjectName("raw_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.raw_5)
        self.horizontalLayout_23.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_23.setSpacing(100)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.tech_support = QtWidgets.QLineEdit(self.raw_5)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.tech_support.setFont(font)
        self.tech_support.setAlignment(QtCore.Qt.AlignCenter)
        self.tech_support.setObjectName("tech_support")
        self.horizontalLayout_23.addWidget(self.tech_support)
        self.streaming_tv = QtWidgets.QLineEdit(self.raw_5)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.streaming_tv.setFont(font)
        self.streaming_tv.setAlignment(QtCore.Qt.AlignCenter)
        self.streaming_tv.setObjectName("streaming_tv")
        self.horizontalLayout_23.addWidget(self.streaming_tv)
        self.streaming_movies = QtWidgets.QLineEdit(self.raw_5)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.streaming_movies.setFont(font)
        self.streaming_movies.setAlignment(QtCore.Qt.AlignCenter)
        self.streaming_movies.setObjectName("streaming_movies")
        self.horizontalLayout_23.addWidget(self.streaming_movies)
        self.verticalLayout_11.addWidget(self.raw_5)
        self.raw_6 = QtWidgets.QWidget(self.customer_data_box)
        self.raw_6.setObjectName("raw_6")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.raw_6)
        self.horizontalLayout_24.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_24.setSpacing(100)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.contract = QtWidgets.QLineEdit(self.raw_6)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.contract.setFont(font)
        self.contract.setAlignment(QtCore.Qt.AlignCenter)
        self.contract.setObjectName("contract")
        self.horizontalLayout_24.addWidget(self.contract)
        self.paperless_billing = QtWidgets.QLineEdit(self.raw_6)

        font = QtGui.QFont()
        font.setPointSize(15)
        self.paperless_billing.setFont(font)
        self.paperless_billing.setAlignment(QtCore.Qt.AlignCenter)
        self.paperless_billing.setObjectName("paperless_billing")
        self.horizontalLayout_24.addWidget(self.paperless_billing)
        self.payment_method = QtWidgets.QLineEdit(self.raw_6)

        font = QtGui.QFont()
        font.setPointSize(15)
        self.payment_method.setFont(font)
        self.payment_method.setAlignment(QtCore.Qt.AlignCenter)
        self.payment_method.setObjectName("payment_method")
        self.horizontalLayout_24.addWidget(self.payment_method)
        self.verticalLayout_11.addWidget(self.raw_6)
        self.widgetraw_7 = QtWidgets.QWidget(self.customer_data_box)
        self.widgetraw_7.setObjectName("widgetraw_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widgetraw_7)
        self.horizontalLayout_21.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_21.setSpacing(100)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")

        self.monthly_charges = QtWidgets.QLineEdit(self.widgetraw_7)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.monthly_charges.setFont(font)
        self.monthly_charges.setAlignment(QtCore.Qt.AlignCenter)
        self.monthly_charges.setObjectName("monthly_charges")
        self.horizontalLayout_21.addWidget(self.monthly_charges)
        self.total_charges = QtWidgets.QLineEdit(self.widgetraw_7)


        font = QtGui.QFont()
        font.setPointSize(15)
        self.total_charges.setFont(font)
        self.total_charges.setAlignment(QtCore.Qt.AlignCenter)
        self.total_charges.setObjectName("total_charges")
        self.horizontalLayout_21.addWidget(self.total_charges)
        self.verticalLayout_11.addWidget(self.widgetraw_7)
        self.verticalLayout_10.addWidget(self.customer_data_box)
        self.predict_container = QtWidgets.QWidget(self.customer_container)
        self.predict_container.setStyleSheet("")
        self.predict_container.setObjectName("predict_container")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.predict_container)
        self.horizontalLayout_25.setContentsMargins(500, 25, 500, 25)
        self.horizontalLayout_25.setSpacing(10)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.predict_btn = QtWidgets.QPushButton(self.predict_container)
        def testt():
                log = logistic_pridect('Female', 0, 'Yes', 'No', 1, 'Yes', 'No phone service', 'DSL', 'No', 'No', 'No', 'No',
                                 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 29.85, '29.85')
                svm_predict = svm_pridect('Female', 0, 'Yes', 'No', 1, 'Yes', 'No phone service', 'DSL', 'No', 'No', 'No', 'No', 'No',
                            'Yes', 'Month-to-month', 'Yes', 'Electronic check', 29.85, '29.85')
                id3_predict = DecicionTree_pridect('Female', 0, 'Yes', 'No', 1, 'Yes', 'No phone service', 'DSL', 'No', 'No', 'No',
                                     'No', 'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 29.85, '29.85')
                naive_predict = Naive_pridect('Female', 0, 'Yes', 'No', 1, 'Yes', 'No phone service', 'DSL', 'No', 'No', 'No', 'No',
                              'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 29.85, '29.85')
                random_predict = Random_pridect('Female', 0, 'Yes', 'No', 1, 'Yes', 'No phone service', 'DSL', 'No', 'No', 'No', 'No',
                               'No', 'Yes', 'Month-to-month', 'Yes', 'Electronic check', 29.85, '29.85')
                if (log[0] == 1):
                        algo_1_answer_txt.setText("Yes")
                else:
                        algo_1_answer_txt.setText("No")
                if (svm_predict[0] == 1):
                        algo_2_answer_txt.setText("Yes")
                else:
                        algo_2_answer_txt.setText("No")
                if (id3_predict[0] == 1):
                        algo_3_answer_txt.setText("Yes")
                else:
                        algo_3_answer_txt.setText("No")
                if (naive_predict[0] == 1):
                        algo_4_answer_txt.setText("Yes")
                else:
                        algo_4_answer_txt.setText("No")
                if (random_predict[0] == 1):
                        algo_5_answer_txt.setText("Yes")
                else:
                        algo_5_answer_txt.setText("No")


        def check_types():


                data = [19]
                data[0] = "Female"#str(self.gender.text())
                data[1] = 0#int(self.senior_sitizen.text())
                data[2] = "Yes"#str(self.partner.text())
                data[3] = "No"#str(self.dependent.text())
                data[4] = 1#int(self.tenure.text())
                data[5] = "Yes"#str(self.phone_service.text())
                data[6] = "No"#str(self.multiple_lines.text())
                data[7] = "phone"#str(self.internet_service.text())
                data[8] = "service"#str(self.online_security.text())
                data[9] = "DSL"#str(self.onlin_backup.text())
                data[10] = "No"#str(self.device_protection.text())
                data[11] = "No"#str(self.tech_support.text())
                data[12] = "No"#str(self.streaming_tv.text())
                data[13] = "No"#str(self.streaming_movies.text())
                data[14] = "No"#str(self.contract.text())
                data[15] = "Yes"#str(self.paperless_billing.text())
                data[16] = 'Month-to-month'#str(self.payment_method.text())
                data[17] = 29.85#float(self.monthly_charges.text())
                data[18] = "29.85"#str(self.total_charges.text())
                return data


        def algo_predict():
                #cust_id_val = cust_id.text()

                #gender_val = gender.text()
                #tenure_val = tenure.text()
                #partner_val = partner.text()
                #internet_service_val = internet_service.text()
                #senior_val = senior.text()
                #dependent_val = dependent.text()
                #onlin_backup_val = onlin_backup.text()
                #streaming_movies_val = streaming_movies.text()
                #device_protection_val = device_protection.text()
                #multiple_lines_val = multiple_lines.text()
                #phone_service_val = phone_service.text()
                #tech_support_val = tech_support.text()
                #streaming_tv_val = streaming_tv.text()
                #total_charges_val = total_charges.text()
                #monthly_charges_val = monthly_charges.text()
                #payment_method_val = payment_method.text()
                #paperless_billing_val = paperless_billing.text()
                #contract_val = contract.text()
                #online_security_val = online_security.text()
                data0 = self.gender.text()
                data1 = self.senior_sitizen.text()
                data2 = self.partner.text()
                data3 = self.dependent.text()
                data4 = self.tenure.text()
                data5 = self.phone_service.text()
                data6 = self.multiple_lines.text()
                data7 = self.internet_service.text()
                data8 = self.online_security.text()
                data9 = self.onlin_backup.text()
                data10 = self.device_protection.text()
                data11 = self.tech_support.text()
                data12 = self.streaming_tv.text()
                data13 = self.streaming_movies.text()
                data14 = self.contract.text()
                data15 = self.paperless_billing.text()
                data16 = self.payment_method.text()
                data17 = self.monthly_charges.text()
                data18 = self.total_charges.text()
                log = logistic_pridect(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18)
                if(log[0] == 1):
                        algo_1_answer_txt.setText("Yes")
                else:
                        algo_1_answer_txt.setText("No")
                svm_predict = svm_pridect(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18)
                if (svm_predict[0] == 1):
                        algo_2_answer_txt.setText("Yes")
                else:
                        algo_2_answer_txt.setText("No")
                id3_predict = DecicionTree_pridect(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18)
                if (id3_predict[0] == 1):
                        algo_3_answer_txt.setText("Yes")
                else:
                        algo_3_answer_txt.setText("No")
                naive_predict = Naive_pridect(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18)
                if (naive_predict[0] == 1):
                        algo_4_answer_txt.setText("Yes")
                else:
                        algo_4_answer_txt.setText("No")
                random_predict = Random_pridect(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18)
                if (random_predict[0] == 1):
                        algo_5_answer_txt.setText("Yes")
                else:
                        algo_5_answer_txt.setText("No")
        self.predict_btn.clicked.connect(algo_predict)





        font = QtGui.QFont()
        font.setPointSize(20)
        self.predict_btn.setFont(font)
        self.predict_btn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.predict_btn.setObjectName("predict_btn")
        self.horizontalLayout_25.addWidget(self.predict_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.predict_container)
        self.cancel_btn.clicked.connect(to_home_page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"    border: 2px solid ;\n"
"    border-radius: 20px;\n"
"    border-color: #77a0d9;\n"
"    background-color:#111b21;\n"
"    fixed-width: 80px;\n"
"    margin-left: 20px;\n"
"    margin-right:20px;\n"
"    margin-bottom:10px;\n"
"    margin-top : 10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5682bf;\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_25.addWidget(self.cancel_btn)
        self.verticalLayout_10.addWidget(self.predict_container)
        self.predict_answer = QtWidgets.QWidget(self.customer_container)
        self.predict_answer.setStyleSheet("")
        self.predict_answer.setObjectName("predict_answer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.predict_answer)
        self.verticalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.algorith_name = QtWidgets.QWidget(self.predict_answer)
        self.algorith_name.setObjectName("algorith_name")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.algorith_name)
        self.horizontalLayout_26.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_26.setSpacing(10)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.algo_name = QtWidgets.QLabel(self.algorith_name)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_name.setFont(font)
        self.algo_name.setObjectName("algo_name")
        self.horizontalLayout_26.addWidget(self.algo_name)
        self.algo_1 = QtWidgets.QLabel(self.algorith_name)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_1.setFont(font)
        self.algo_1.setObjectName("algo_1")
        self.horizontalLayout_26.addWidget(self.algo_1)
        self.algo_2 = QtWidgets.QLabel(self.algorith_name)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_2.setFont(font)
        self.algo_2.setObjectName("algo_2")
        self.horizontalLayout_26.addWidget(self.algo_2)
        self.algo_3 = QtWidgets.QLabel(self.algorith_name)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_3.setFont(font)
        self.algo_3.setObjectName("algo_3")
        self.horizontalLayout_26.addWidget(self.algo_3)
        self.algo_4 = QtWidgets.QLabel(self.algorith_name)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_4.setFont(font)
        self.algo_4.setObjectName("algo_4")
        self.horizontalLayout_26.addWidget(self.algo_4)
        self.algo_5 = QtWidgets.QLabel(self.algorith_name)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_5.setFont(font)
        self.algo_5.setObjectName("algo_5")
        self.horizontalLayout_26.addWidget(self.algo_5)
        self.verticalLayout_12.addWidget(self.algorith_name)
        self.answer_container = QtWidgets.QWidget(self.predict_answer)
        self.answer_container.setObjectName("answer_container")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.answer_container)
        self.horizontalLayout_27.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_27.setSpacing(10)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.predict_answer_lb = QtWidgets.QLabel(self.answer_container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.predict_answer_lb.setFont(font)
        self.predict_answer_lb.setObjectName("predict_answer_lb")
        self.horizontalLayout_27.addWidget(self.predict_answer_lb)
        algo_1_answer_txt = self.algo_1_answer = QtWidgets.QLabel(self.answer_container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_1_answer.setFont(font)
        self.algo_1_answer.setText("")
        self.algo_1_answer.setObjectName("algo_1_answer")
        self.horizontalLayout_27.addWidget(self.algo_1_answer)
        algo_2_answer_txt = self.algo_2_answer = QtWidgets.QLabel(self.answer_container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_2_answer.setFont(font)
        self.algo_2_answer.setText("")
        self.algo_2_answer.setObjectName("algo_2_answer")
        self.horizontalLayout_27.addWidget(self.algo_2_answer)
        algo_3_answer_txt = self.algo_3_answer = QtWidgets.QLabel(self.answer_container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_3_answer.setFont(font)
        self.algo_3_answer.setText("")
        self.algo_3_answer.setObjectName("algo_3_answer")
        self.horizontalLayout_27.addWidget(self.algo_3_answer)
        algo_4_answer_txt = self.algo_4_answer = QtWidgets.QLabel(self.answer_container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_4_answer.setFont(font)
        self.algo_4_answer.setText("")
        self.algo_4_answer.setObjectName("algo_4_answer")
        self.horizontalLayout_27.addWidget(self.algo_4_answer)
        algo_5_answer_txt = self.algo_5_answer = QtWidgets.QLabel(self.answer_container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.algo_5_answer.setFont(font)
        self.algo_5_answer.setText("")
        self.algo_5_answer.setObjectName("algo_5_answer")
        self.horizontalLayout_27.addWidget(self.algo_5_answer)
        self.verticalLayout_12.addWidget(self.answer_container)
        self.verticalLayout_10.addWidget(self.predict_answer)
        self.verticalLayout_10.setStretch(0, 8)
        self.verticalLayout_10.setStretch(1, 1)
        self.verticalLayout_10.setStretch(2, 1)
        self.gridLayout_3.addWidget(self.customer_container, 0, 0, 1, 1)
        self.all_page.addWidget(self.customer)
        self.verticalLayout.addWidget(self.all_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Service Cancellation Predictor"))
        self.program_name_2.setText(_translate("MainWindow", "Service cancellation\n"
"predictor"))
        self.train_test_main_2.setText(_translate("MainWindow", "Methodology"))
        self.predict_main_2.setText(_translate("MainWindow", "Predict"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.logistic_box.setText(_translate("MainWindow", "Logistic Regression"))
        self.svm_box.setText(_translate("MainWindow", "SVM"))
        self.id3_box.setText(_translate("MainWindow", "ID3"))
        self.naive_box.setText(_translate("MainWindow", "Naive"))
        self.random_box.setText(_translate("MainWindow", "Random"))
        self.train_btn.setText(_translate("MainWindow", "Train"))
        self.test_btn.setText(_translate("MainWindow", "Test"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.lb_1.setText(_translate("MainWindow", "Logistic Regression"))
        self.lb_2.setText(_translate("MainWindow", "Accuracy"))
        self.lb_3.setText(_translate("MainWindow", "Precision"))
        self.lb_4.setText(_translate("MainWindow", "Recall"))
        self.lb_5.setText(_translate("MainWindow", "F1 Score"))
        self.lb_6.setText(_translate("MainWindow", "Train"))
        self.lb_11.setText(_translate("MainWindow", "Test"))
        self.lb_16.setText(_translate("MainWindow", "SVM"))
        self.lb_17.setText(_translate("MainWindow", "Accuracy"))
        self.lb_19.setText(_translate("MainWindow", "Precision"))
        self.lb_18.setText(_translate("MainWindow", "Recall"))
        self.lb_20.setText(_translate("MainWindow", "F1 Score"))
        self.lb_24.setText(_translate("MainWindow", "Train"))
        self.lb_26.setText(_translate("MainWindow", "Test"))
        self.lb_31.setText(_translate("MainWindow", "ID3"))
        self.lb_32.setText(_translate("MainWindow", "Accuracy"))
        self.lb_34.setText(_translate("MainWindow", "Precision"))
        self.lb_33.setText(_translate("MainWindow", "Recall"))
        self.lb_35.setText(_translate("MainWindow", "F1 Score"))
        self.lb_39.setText(_translate("MainWindow", "Train"))
        self.lb_41.setText(_translate("MainWindow", "Test"))
        self.lb_48.setText(_translate("MainWindow", "Naive"))
        self.lb_46.setText(_translate("MainWindow", "Accuracy"))
        self.lb_49.setText(_translate("MainWindow", "Precision"))
        self.lb_47.setText(_translate("MainWindow", "Recall"))
        self.lb_50.setText(_translate("MainWindow", "F1 Score"))
        self.lb_51.setText(_translate("MainWindow", "Train"))
        self.lb_59.setText(_translate("MainWindow", "Test"))
        self.lb_63.setText(_translate("MainWindow", "Random"))
        self.lb_61.setText(_translate("MainWindow", "Accuracy"))
        self.lb_64.setText(_translate("MainWindow", "Precision"))
        self.lb_62.setText(_translate("MainWindow", "Recall"))
        self.lb_65.setText(_translate("MainWindow", "F1 Score"))
        self.lb_66.setText(_translate("MainWindow", "Train"))
        self.lb_74.setText(_translate("MainWindow", "Test"))
        self.customer_id.setPlaceholderText(_translate("MainWindow", "Customer_id"))
        self.gender.setPlaceholderText(_translate("MainWindow", "Gender"))
        self.senior_sitizen.setPlaceholderText(_translate("MainWindow", "Senior Sitizen"))
        self.partner.setPlaceholderText(_translate("MainWindow", "Partner"))
        self.dependent.setPlaceholderText(_translate("MainWindow", "Dependent"))
        self.tenure.setPlaceholderText(_translate("MainWindow", "Tenure"))
        self.phone_service.setPlaceholderText(_translate("MainWindow", "Phone Service"))
        self.multiple_lines.setPlaceholderText(_translate("MainWindow", "Multiple Lines"))
        self.internet_service.setPlaceholderText(_translate("MainWindow", "Internet Service"))
        self.online_security.setPlaceholderText(_translate("MainWindow", "Online Security"))
        self.onlin_backup.setPlaceholderText(_translate("MainWindow", "Online Backup"))
        self.device_protection.setPlaceholderText(_translate("MainWindow", "Device Protection"))
        self.tech_support.setPlaceholderText(_translate("MainWindow", "Tech Support"))
        self.streaming_tv.setPlaceholderText(_translate("MainWindow", "Streaming Tv"))
        self.streaming_movies.setPlaceholderText(_translate("MainWindow", "Streaming Movies"))
        self.contract.setPlaceholderText(_translate("MainWindow", "Contract"))
        self.paperless_billing.setPlaceholderText(_translate("MainWindow", "Paperless Billing"))
        self.payment_method.setPlaceholderText(_translate("MainWindow", "Payment Method"))
        self.monthly_charges.setPlaceholderText(_translate("MainWindow", "Monthly Charges"))
        self.total_charges.setPlaceholderText(_translate("MainWindow", "Total Charges"))
        self.predict_btn.setText(_translate("MainWindow", "Predict"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.algo_name.setText(_translate("MainWindow", "Algorithm Name"))
        self.algo_1.setText(_translate("MainWindow", "Logistic Regression"))
        self.algo_2.setText(_translate("MainWindow", "SVM"))
        self.algo_3.setText(_translate("MainWindow", "ID3"))
        self.algo_4.setText(_translate("MainWindow", "Naive"))
        self.algo_5.setText(_translate("MainWindow", "Random"))
        self.predict_answer_lb.setText(_translate("MainWindow", "Prediction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
